### ISSUE TITLE
Using firebase to store data

### ISSUE THREAD

**Issue by ZiyangWu1** [XZSCOAX57/COMP8715-EnergyStorageRight#108]

**Comment by u7518297** [comment]
The final decision has been made by both the team and the client. Check the live agenda and meeting minutes for discussion details: 
https://docs.google.com/document/d/1vaShTXUZBZq2byqJBbbNd8weWz5i0LLBVcMQ1477_34/edit?usp=sharing
https://docs.google.com/document/d/1Y2axAe-6VYfA9Dh7QbdD-N1tEq3vyLWYqUfciIJks7U/edit?usp=sharing
